# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger: 
- main

name: $(increment)

pool:
  vmImage: 'windows-latest'

variables: 
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  buildMajor: '$(Major)'
  buildMinor: '$(Minor)'
  buildRevision: '$(Revision)'
  increment: $[counter(1,0)]

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    feedsToUse: 'select'
    vstsFeed: 'AzureFeed_Projects'
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/property:Major=$(buildMajor);Minor=$(buildMinor);Revision=$(buildRevision);Build=$(Build.BuildNumber);VersionAssembly=$(buildMajor).$(buildMinor).$(buildRevision).$(Build.BuildNumber)'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'Source\Plugin\Installer\bin\**\en-us\*.msi' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true
    overWrite: true
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Setups'